apiVersion: v1
kind: Service
metadata:
  labels:
    app: vengineers-frontend

  name: vengineers-frontend-svc
spec:
  ports:
  - name: "vite"
    port: 5173
    protocol: TCP
    targetPort: 5173
  selector:
    app: vengineers-frontend
  type: ClusterIP
status:
  loadBalancer: {}

