apiVersion: v1
kind: ConfigMap
metadata:
  name: vengineers-backend-config
data:
  APP_NAME: Vengineers

  APP_LOCALE: en
  APP_FALLBACK_LOCALE: en
  

  APP_MAINTENANCE_DRIVER: file
  BCRYPT_ROUNDS: 12

  LOG_CHANEL: stack
  LOG_STACK: single
  LOG_DEPRECATIONS_CHANNEL: null

  SESSION_DRIVER: database
  SESSION_LIFETIME: 120
  SESSION_ENCRYPT: false
  SESSION_PATH: '/'
  SESSION_DOMAIN: localhost

  BROADCAST_CONNECTION: log
  FILESYSTEM_DISK: local
  QUEUE_CONNECTION: database
  CACHE_STORE: database

  MAIL_MAILER: log
  MAIL_FROM_ADDRESS: 'contact@vengineers.net'
  MAIL_FROM_NAME: 'Vengineers'


