apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vengineers-backend
  name: vengineers-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vengineers-backend
  strategy:
    type: RollingUpdate
    maxSurge: 1
    maxUnavailable: 1
  template:
    metadata:
      labels:
        app: vengineers-backend
    spec:
      containers:
      - image: prasolonjatovo/vengineers-backend:dev
        name: vengineers-backend
        envFrom:
        - configMapRef:
            name: vengineers-backend-config
        ports:
        - containerPort: 9000
      
      volumes:
      - name: vengineers-backend-volume
        configMap:
          name: vengineers-backend-config
          path: vengineers-backend-config
