apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vengineers-backend
  name: vengineers-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vengineers-backend
  template:
    metadata:
      labels:
        app: vengineers-backend
    spec:
      containers:
      - image: prasolonjatovo/vengineers-backend:dev
        name: vengineers-backend
        envFrom:
        - configMapRef:
            name: vengineers-backend-config
        - secretRef:
            name: vengineers-backend-secret
        ports:
        - containerPort: 9000
