apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vengineers-backend
  name: vengineers-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vengineers-backend
  template:
    metadata:
      labels:
        app: vengineers-backend
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z mysql-svc 3306; do
                echo "En attente de MySQL..."
                sleep 2
              done
      containers:
      - image: prasolonjatovo/vengineers-backend:dev
        name: vengineers-backend
        envFrom:
        - configMapRef:
            name: vengineers-backend-config
        - secretRef:
            name: vengineers-backend-secret
        ports:
        - containerPort: 9000
